import type { Metadata } from "next";
import { Montserrat as FontSans } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const fontSans = FontSans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "All One",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fontSans.className}><NavBar />{children}</body>
    </html>
  );
}
